name: Run tests at every commit
run-name: ${{ github.actor }} is running the test at every commit

on: [push]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Specifica una versione Python compatibile

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Installa pytest (aggiungi altre dipendenze se necessarie)

      # Step 4: Run the tests
      - name: Run tests
        run: |
          pytest